# Generated by Django 3.0.14 on 2024-04-03 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InstagramDownload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.CharField(max_length=200)),
                ('caption', models.TextField(blank=True)),
                ('like', models.TextField(blank=True)),
                ('username', models.CharField(max_length=100)),
                ('date', models.DateTimeField()),
            ],
        ),
    ]
